Repository stackabletech/trino-operator, pull requests merged in 2025-03, with the labels that each got.

#718 chore: Update ZooKeeper to 3.9.3 pre-25.3.0
  tests/test-definition.yaml
Labels: release/25.3.0

#713 feat: Support removing properties from catalogs
  CHANGELOG.md
  deploy/helm/trino-operator/crds/crds.yaml
  docs/modules/trino/pages/usage-guide/catalogs/index.adoc
  rust/operator-binary/src/catalog/config.rs
  rust/operator-binary/src/crd/catalog/mod.rs
Labels: customer-request, scheduled-for/25.3.0

#722 chore: Bump Rust dependencies pre-25.3.0
  CHANGELOG.md
  Cargo.lock
  Cargo.nix
  Cargo.toml
  crate-hashes.json
Labels: release/25.3.0

#725 docs: Mark Trino 455 as deprecated
  docs/modules/trino/partials/supported-versions.adoc
Labels: scheduled-for/25.3.0
